import { NextResponse } from 'next/server'
import { getDailySeed } from '@/lib/game/daily-seed'
import { supabase } from '@/lib/db/supabase'
import { GameItem } from '@/lib/game/types'

export const dynamic = 'force-dynamic'
export const revalidate = 0

/**
 * Get today's Spotify game from database
 * Games are pre-generated by cron job at midnight
 */
export async function GET() {
  try {
    const dateSeed = getDailySeed()
    
    // Get today's game from database
    const { data: dailyItems, error } = await supabase
      .from('daily_games')
      .select('*')
      .eq('category', 'spotify')
      .eq('game_date', dateSeed)
      .order('position')
    
    if (error) {
      console.error('Database error:', error)
      throw error
    }
    
    if (!dailyItems || dailyItems.length < 6) {
      console.log(`⚠️ No prepared game for ${dateSeed}, generating on-demand...`)
      
      // Fallback: Generate on-demand from kworb
      const { scrapeSpotifyListeners, artistsToGameItems, getArtistPlaceholder } = await import('@/lib/api/kworb-scraper')
      const { searchSpotifyArtist, getBestSpotifyImage } = await import('@/lib/api/spotify-api')
      const { seededShuffle } = await import('@/lib/game/daily-seed')
      
      const scrapedArtists = await scrapeSpotifyListeners()
      if (scrapedArtists.length === 0) {
        return NextResponse.json(
          { error: 'Failed to fetch artists' },
          { status: 500 }
        )
      }
      
      const allArtists = artistsToGameItems(scrapedArtists)
      const shuffled = seededShuffle(allArtists, dateSeed)
      const selected = shuffled.slice(0, 6)
      
      // Fetch images
      const itemsWithImages = await Promise.all(
        selected.map(async (artist, index) => {
          try {
            const spotifyData = await searchSpotifyArtist(artist.name)
            const imageUrl = spotifyData ? getBestSpotifyImage(spotifyData.images) : ''
            
            return {
              ...artist,
              imageUrl: imageUrl || getArtistPlaceholder(artist.name),
              value: index === 0 ? artist.value : 0, // Hide values except first
            }
          } catch (error) {
            console.error(`Failed to fetch image for ${artist.name}:`, error)
            return {
              ...artist,
              value: index === 0 ? artist.value : 0,
            }
          }
        })
      )
      
      console.log(`✅ Generated on-demand Spotify game for ${dateSeed}`)
      
      return NextResponse.json({
        category: 'spotify',
        date: dateSeed,
        items: itemsWithImages,
        source: 'on-demand',
      })
    }
    
    // Convert to GameItems - HIDE VALUES except first one
    const items: GameItem[] = dailyItems.map((item, index) => ({
      id: item.external_id || '',
      name: item.name,
      value: index === 0 ? Number(item.value) : 0, // Only send first value
      imageUrl: item.image_url || '',
      subtitle: item.subtitle || '',
    }))
    
    console.log(`✅ Loaded Spotify game for ${dateSeed} from database`)
    
    return NextResponse.json({
      category: 'spotify',
      date: dateSeed,
      items,
      source: 'database',
    })
  } catch (error) {
    console.error('❌ Error loading spotify game:', error)
    return NextResponse.json(
      { error: 'Failed to load game', details: String(error) },
      { status: 500 }
    )
  }
}
