import { NextResponse } from 'next/server'
import { getDailySeed } from '@/lib/game/daily-seed'
import { supabase } from '@/lib/db/supabase'
import { GameItem } from '@/lib/game/types'

export const dynamic = 'force-dynamic'
export const revalidate = 0

/**
 * Get today's Movies game from database
 * Games are pre-generated by cron job at midnight
 */
export async function GET() {
  try {
    const dateSeed = getDailySeed()
    
    // Get today's game from database
    const { data: dailyItems, error } = await supabase
      .from('daily_games')
      .select('*')
      .eq('category', 'movies')
      .eq('game_date', dateSeed)
      .order('position')
    
    if (error) {
      console.error('Database error:', error)
      throw error
    }
    
    if (!dailyItems || dailyItems.length < 6) {
      console.log(`⚠️ No prepared game for ${dateSeed}, generating on-demand...`)
      
      // Fallback: Generate on-demand from movies_pool
      const { data: poolMovies } = await supabase
        .from('movies_pool')
        .select('*')
        .limit(100)
      
      if (!poolMovies || poolMovies.length === 0) {
        return NextResponse.json(
          { 
            error: 'No movies available. Please run: npm run populate-movies',
          },
          { status: 500 }
        )
      }
      
      // Use date seed to pick 6
      const { seededShuffle } = await import('@/lib/game/daily-seed')
      const movieItems = poolMovies.map(m => ({ id: m.imdb_id, data: m }))
      const shuffled = seededShuffle(movieItems, dateSeed)
      const selected = shuffled.slice(0, 6)
      
      // Fetch IMDB ratings
      const { fetchOMDBRating } = await import('@/lib/api/omdb')
      const items: GameItem[] = []
      
      for (const item of selected) {
        const movie = item.data
        const omdbData = await fetchOMDBRating(movie.imdb_id)
        
        if (omdbData && omdbData.imdbRating && omdbData.imdbRating !== 'N/A') {
          items.push({
            id: movie.imdb_id,
            name: movie.title,
            value: parseFloat(omdbData.imdbRating),
            imageUrl: omdbData.Poster !== 'N/A' ? omdbData.Poster : movie.poster_url,
            subtitle: movie.year,
          })
        }
        
        if (items.length >= 6) break
      }
      
      if (items.length < 6) {
        return NextResponse.json(
          { error: 'Failed to fetch enough movies with ratings' },
          { status: 500 }
        )
      }
      
      // Hide values except first
      const hiddenItems = items.map((item, index) => ({
        ...item,
        value: index === 0 ? item.value : 0,
      }))
      
      console.log(`✅ Generated on-demand Movies game for ${dateSeed}`)
      
      return NextResponse.json({
        category: 'movies',
        date: dateSeed,
        items: hiddenItems,
        source: 'on-demand',
      })
    }
    
    // Convert to GameItems - HIDE VALUES except first one
      const items: GameItem[] = dailyItems.map((item, index) => ({
        id: item.external_id || '',
        name: item.name,
        value: index === 0 ? Number(item.value) : 0, // Only send first value
        imageUrl: item.image_url || '',
      subtitle: item.subtitle || '',
      }))
      
    console.log(`✅ Loaded Movies game for ${dateSeed} from database`)
      
      return NextResponse.json({
        category: 'movies',
        date: dateSeed,
        items,
      source: 'database',
    })
  } catch (error) {
    console.error('❌ Error loading movies game:', error)
    return NextResponse.json(
      { error: 'Failed to load game', details: String(error) },
      { status: 500 }
    )
  }
}

